### ISSUE TITLE
randomElements fail on windows

### ISSUE THREAD

**Issue by Canadadry** [fzaninotto/Faker#1415] opened 2018-01-31 13:44 UTC
I use faker for my fixture in a symfony project mainly developp on mac and deploy on a debian 8 without any issue.
But one of my team member use windows and will setting up the project, faker fail with a ` Notice: Undefined offset: -25` here the full stack

```
D:\xampp\htdocs\api>php bin/console d:f:l --append -v
 > loading ApiSecurityBundle\DataFixtures\ORM\LoadUser

 [Symfony\Component\Debug\Exception\ContextErrorException]
 Notice: Undefined offset: -25

Exception trace:
() at D:\xampp\htdocs\api\vendor\fzaninotto\faker\src\Faker\Provider\Base.php:194
Faker\Provider\Base::randomElements() at D:\xampp\htdocs\api\vendor\fzaninotto\faker\src\Faker\Provider\Base.php:212
Faker\Provider\Base::randomElement() at D:\xampp\htdocs\api\vendor\fzaninotto\faker\src\Faker\Provider\Person.php:78
Faker\Provider\Person::firstNameMale() at n/a:n/a
call_user_func_array() at D:\xampp\htdocs\api\vendor\fzaninotto\faker\src\Faker\Generator.php:222
Faker\Generator->format() at D:\xampp\htdocs\api\vendor\fzaninotto\faker\src\Faker\Generator.php:268
Faker\Generator->__get() at D:\xampp\htdocs\api\src\ApiSecurityBundle\DataFixtures\ORM\LoadUser.php:106
ApiSecurityBundle\DataFixtures\ORM\LoadUser->createIdentityForUSer() at D:\xampp\htdocs\api\src\ApiSecurityBundle\DataFixtures\ORM\LoadUser.php:62
ApiSecurityBundle\DataFixtures\ORM\LoadUser->buildUser() at D:\xampp\htdocs\api\src\ApiSecurityBundle\DataFixtures\ORM\LoadUser.php:44
ApiSecurityBundle\DataFixtures\ORM\LoadUser->load() at D:\xampp\htdocs\api\vendor\doctrine\data-fixtures\lib\Doctrine\Common\DataFixtures\Executor\AbstractExecutor.php:121
Doctrine\Common\DataFixtures\Executor\AbstractExecutor->load() at D:\xampp\htdocs\api\vendor\doctrine\data-fixtures\lib\Doctrine\Common\DataFixtures\Executor\ORMExecutor.php:88
Doctrine\Common\DataFixtures\Executor\ORMExecutor->Doctrine\Common\DataFixtures\Executor\{closure}() at n/a:n/a
call_user_func() at D:\xampp\htdocs\api\vendor\doctrine\orm\lib\Doctrine\ORM\EntityManager.php:233
Doctrine\ORM\EntityManager->transactional() at D:\xampp\htdocs\api\var\cache\dev\appDevDebugProjectContainer.php:6331
DoctrineORMEntityManager_00000000373d2bb00000000064d026a8a0621a96f7214a5a7263dc557f6c986e->transactional() at D:\xampp\htdocs\api\vendor\doctrine\data-fixtures\lib\Doctrine\Common\DataFixtures\Executor\ORMExecutor.php:90
Doctrine\Common\DataFixtures\Executor\ORMExecutor->execute() at D:\xampp\htdocs\api\vendor\doctrine\doctrine-fixtures-bundle\Command\LoadDataFixturesDoctrineCommand.php:119
Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand->execute() at D:\xampp\htdocs\api\vendor\symfony\symfony\src\Symfony\Component\Console\Command\Command.php:264
Symfony\Component\Console\Command\Command->run() at D:\xampp\htdocs\api\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:859
Symfony\Component\Console\Application->doRunCommand() at D:\xampp\htdocs\api\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:206
Symfony\Component\Console\Application->doRun() at D:\xampp\htdocs\api\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php:81
Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at D:\xampp\htdocs\api\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:125
Symfony\Component\Console\Application->run() at D:\xampp\htdocs\api\bin\console:28
```

Here some more information about my usage of faker in `LoadUser.php`

```
<?php 
namespace ApiSecurityBundle\DataFixtures\ORM;

use Symfony\Component\DependencyInjection\ContainerAwareInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Doctrine\Common\DataFixtures\FixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use ApiSecurityBundle\Entity\User;
use ApiSecurityBundle\Entity\UserRole;
use ApiSecurityBundle\Entity\UserIdentity;
use ApiSecurityBundle\Entity\AuthToken;

use Faker\Factory as FakerFactory;

class LoadUser implements FixtureInterface, ContainerAwareInterface
{

	/**
	* @var ContainerInterface
	*/
	protected $container;
	protected $manager;

	public function setContainer(ContainerInterface $container = null)
	{
		$this->container = $container;
	}

	public function load(ObjectManager $manager)
	{
		$this->manager = $manager;
		$this->faker= FakerFactory::create('fr_FR');
		$this->faker->seed(0);

		$this->buildUser([
			['name'=>'admin1','role'=>UserRole::CLIENT],
			['name'=>'admin2','role'=>UserRole::CLIENT],
			['name'=>'admin3','role'=>UserRole::CLIENT],
			['name'=>'admin4','role'=>UserRole::CLIENT],
			['name'=>'applicant','role'=>UserRole::APPLICANT],
			['name'=>'checker','role'=>UserRole::CHECKER],
			['name'=>'trader','role'=>UserRole::TRADER],
			['name'=>'independent','role'=>UserRole::INDEPENDENT],
			['name'=>'trueadmin','role'=>UserRole::ADMIN],
		]);

		$this->manager->flush();
	}

	public function buildUser(Array $users)
	{
		foreach ($users as  $user) 
		{
			if(array_key_exists('isNameAnEmail', $user) == false)
			{
				$user['isNameAnEmail'] = false;
			}
			$this->users[] = $this->createIdentityForUSer(
				$this->createToken(
					$this->createUser($user['name'],$user['role'],$user['isNameAnEmail'])
				)
				,$user['role'] == UserRole::CLIENT                            
			);
		}

	}

	public function createToken(User $user)
	{
		$authToken = new AuthToken();
		$authToken->setValue('token_'. $user->getPlainPassword() );
		$authToken->setUser($user);
		$authToken->setCreatedAt(new \DateTime('now'));
		$this->manager->persist($authToken);

		return $user;
	}


	public function createUser($name = 'admin', $roleName = UserRole::CLIENT, $isNameAnEmail = false)
	{
		$user = new User();
		$user->setUsername($name);
		$user->setEmail($name . ($isNameAnEmail ? '': '@everycheck.fr'));
		$user->setPlainPassword($name);    
		$user->setLastConnexionDate($this->faker->dateTime($max = 'now'));

		$role = $this->manager->getRepository('ApiSecurityBundle:UserRole')->findOneByName($roleName);
		if($role != null) $user->getRolesCollection()->add($role);
		else {print($roleName); dump($this->manager->getRepository('ApiSecurityBundle:UserRole')->findAll()); die;}


			$encoder = $this->container->get('security.password_encoder');
			$encoded = $encoder->encodePassword($user, $user->getPlainPassword());
			$user->setPassword($encoded);

			$this->manager->persist($user);

			return $user;
		}

		public function createIdentityForUSer(User $user, $withAvatar = false)
		{
			$identity = new UserIdentity();
			$identity->setCivility($this->faker->boolean ? 'Mr' : 'Mme');
			// the line 106 which make faker failed
			$identity->setFirstName($identity->getCivility() == 'Mr' ? $this->faker->firstNameMale : $this->faker->firstNameFemale);
			$identity->setLastname($this->faker->lastname);
			$identity->setCompany($this->faker->company);
			$identity->setPhone($this->faker->phoneNumber);
			$identity->setUser($user);
			
			if ($withAvatar == true)
			{
				$folder = $this->container->getParameter('cache_folder');
				$file = $this->faker->image($folder, 100, 100);
				$identity->setAvatar(base64_encode(file_get_contents($file)));
				unlink($file);
			}
			
			$user->setIdentity($identity);

			$this->manager->persist($identity);
			$this->manager->persist($user);

			return $user;
		}

	}
```

If you need anymore information.

**Comment by anber500** [comment] 2018-02-01 02:36
I can confirm that this happens on my Windows environment as well. I'm using Yii2's "yiisoft/yii2-faker" package which downloads the 1.7.1 release of Faker. I have also tested the 1.7.0 version and it also breaks.

I've downgraded to the 1.60 release of Faker and it seems to work as expected.

**Comment by tomzx** [comment] 2018-02-01 18:16
Hello, this looks like a duplicate of #1379.

**Comment by fzaninotto** [comment] 2018-02-02 13:41
Yep, duplicate bug, closing.

**Closed by fzaninotto** 2018-02-02 13:41 UTC
