### ISSUE TITLE
Generate fake identities that fit to each other

### ISSUE THREAD

**Issue by amenk** [fzaninotto/Faker#1178] opened 2017-03-29 07:36 UTC
Is it possible, for example when generating a name, to generate a mail that fits to it?

For example, Doe, John -> JohnDoe123@gmail.com

The Problem is that we often debug in our database of fake data and it is very confusing when John Doe has a email address that implies another name like MaxMusterman123@gmail.com

Same might apply for company names. John Doe might probably be in the Doe and Sons company.

**Comment by fzaninotto** [comment] 2017-03-29 09:41
Duplicate of #557

**Closed by fzaninotto** 2017-03-29 09:41 UTC

**Comment by amenk** [comment] 2017-03-29 09:42
Thanks for finding the dupe --- but they seem to be closed both now?

**Comment by fzaninotto** [comment] 2017-03-29 09:44
Yes, that's a "won't fix" type of closed.

**Comment by amenk** [comment] 2017-03-29 09:44
But why? Too complicated? Would you accept such a PR ?

**Comment by fzaninotto** [comment] 2017-03-29 09:45
If you want to give it a try, you're welcome. But I don't think the current architecture allows it without breaking BC hard.
