### ISSUE TITLE
doctrine - clear in populator

### ISSUE THREAD

**Issue by devozanges** [fzaninotto/Faker#1870] opened 2019-12-06 16:12 UTC
greeting
when I have to make fixtures with relationships, the populator tells me that my entities are not persisted, so by searching in the `Faker\ORM\Doctrine\Populator` class, I found that there were orm->clear(), it's fine but it makes disappear the entities I join to my relationships so I'm obliged to comment on the clear() so that my fixtures work with relationships.
Do you know if there is a more conventional practice to achieve this?
Thanks for your work anyway

    `public function execute($entityManager = null)
    {
        if (null === $entityManager) {
            $entityManager = $this->manager;
        }
        if (null === $entityManager) {
            throw new \InvalidArgumentException("No entity manager passed to Doctrine Populator.");
        }

        $insertedEntities = [];
        foreach ($this->quantities as $class => $number) {
            $generateId = $this->generateId[$class];
            for ($i = 0; $i < $number; $i++) {

                $insertedEntities[$class][] = $this->entities[$class]->execute(
                    $entityManager,
                    $insertedEntities,
                    $generateId
                );
                if (count($insertedEntities) % $this->batchSize === 0) {
                    $entityManager->flush();
                    // $entityManager->clear($class);
                }
            }
            $entityManager->flush();
            // $entityManager->clear($class);
        }
        return $insertedEntities;
    }`

**Comment by jaapromijn** [comment] 2019-12-09 08:43
I think this is a duplicate of https://github.com/fzaninotto/Faker/issues/1870

**Comment by pimjansen** [comment] 2019-12-16 15:14
Indeed a duplicate

**Closed by pimjansen** 2019-12-16 15:14 UTC
