### ISSUE TITLE
Unknown formatter when class is defined but not the property

### ISSUE THREAD

**Issue by edyan** [fzaninotto/Faker#1468] opened 2018-04-18 12:17 UTC
When using another language than en_US and the main Faker class is defined but not the property, I get a "Unknown formatter"

Example : 
- fr_FR as language
- Method **cityPrefix**

Look at the missing property : 
- The translation is there : https://github.com/fzaninotto/Faker/blob/master/src/Faker/Provider/fr_FR/Address.php
- Parent : https://github.com/fzaninotto/Faker/blob/master/src/Faker/Provider/Address.php
- en_US is right : https://github.com/fzaninotto/Faker/blob/master/src/Faker/Provider/en_US/Address.php

Thanks !
The

**Comment by tomzx** [comment] 2018-04-19 20:32
There's apparently no city prefix for the fr_FR locale.

I have no idea how the providers are built, so I'm not sure how one should add a `cityPrefix` to the `fr_FR` locale. @fzaninotto?

**Comment by edyan** [comment] 2018-04-20 02:26
I think you are right @tomzx ... In the doc that method is available only for en_US so I understand now that there are specific methods for some languages : I did a script to get all providers, languages, etc ... . My intention was to find missing providers. But I got immediately an error with "addBankCodeChecksum" ... because it's only available for `pl_PL`

The issue is that we can expect to change the locale dynamically and keep the same config. Maybe a good practice would be to have a fallback Provider when the one called does not exist ?

Also I found a second issue (not sure it's one, but at least it's strange) : everything inherits from `Base` which means that my Provider `Address` has a method `randomDigitNotNull` :)

**Comment by pimjansen** [comment] 2019-08-27 19:24
@edyan indeed every extends from Base where each provider can easily override the existing base methods.

Concerning the initial question it is indeed true that certain methods do not exist in the locale expected and therefor the error is thrown. This is intended since we can not lock it strict to a specific interface which matches each locale. So all this is as intended.

Since it is not a bug and i do not really see an improvement in here except updating a specific locale i will close this issue

**Closed by pimjansen** 2019-08-27 19:24 UTC
Labels: enhancement
