### ISSUE TITLE
CC-BY-SA-NC code is inside of Faker

### ISSUE THREAD

**Issue by fu7mu4** [fzaninotto/Faker#1236] opened 2017-06-20 12:06 UTC
Line 28-29 of src/Faker/Provider/it_IT/Text.php says its License is CC-BY-SA-NC. I think it is not compatible with MIT License.

**Comment by fzaninotto** [comment] 2017-08-07 15:56
Duplicate of #881

**Closed by fzaninotto** 2017-08-07 15:56 UTC
