### ISSUE TITLE
Length modifier for generators

### ISSUE THREAD

**Issue by hendore** [fzaninotto/Faker#567] opened 2015-05-03 15:20 UTC
More of a feature request than an issue. I'm seeding entities which have constraints such as a username cannot exceed 24 characters etc... It would be great if we could specify this constraint when invoking a generator, similar to `unique` and `optional`. They could even be chained, not sure if `optional` and `unique` are chainable at the moment, not tested. It could look something like:

`$faker->length($min = 0, $max = 24)->unique()->userName`

Would this be a possible feature for a future release?

Diving through the src, looks like we could introduce a `LengthGenerator` class, and then a `length($min = 0, $max = null)` method to the Base provider. Can anyone see any implications on doing this?

**Comment by ikwattro** [comment] 2015-05-03 15:34
The problem is that a length constraint can not be implemented to all providers, and thus can't be applied at a global stage for chaining. For e.g. it can have undesired effetcts to use a length constraint on a Date or EAN provider.

**Comment by hendore** [comment] 2015-05-03 15:38
ikwattro, thank you for such a quick response, that makes sense.

I've just noticed some formatters such as those defined in the Lorem provider allow number of characters to be specified, however those in the Internet provider don't. Would it be more of a case of updating the formatters to take into account a length argument?

**Comment by ikwattro** [comment] 2015-05-03 15:46
Yes it would. Personally, I would : 

* Or Create my own provider on top of the base formatter present in the library (which is so easy to do)
* Or ask to implement `pre` and `post` generation events that would allow you to implement logics based on the formatter called.

**Comment by fzaninotto** [comment] 2015-05-06 16:38
That being said, I like the idea of a general purpose modifier, taking a callable as parameter. If the callable returns true, the value is valid, otherwise the formatter should generate another one.

**Comment by fzaninotto** [comment] 2016-02-23 15:00
Fixed by #836

**Closed by fzaninotto** 2016-02-23 15:00 UTC
