### ISSUE TITLE
VAT formatter does not work in fr_FR namespace

### ISSUE THREAD

**Issue by thomasngataly** [fzaninotto/Faker#1342] opened 2017-11-02 13:33 UTC
Hello,
The error occurs when I try to use the vat formatter. This formatter use the siren method which does not exists in the class and its parent. This method seems to be defined in the Faker\Provider\fr_FR\Company class.

**Comment by raphaeldealmeida** [comment] 2017-11-05 04:21
Hi @thomasngataly 

I think VAT is [Payment Provider](https://github.com/fzaninotto/Faker/blob/master/src/Faker/Provider/fr_FR/Payment.php#L20) 
Give me a code example please

**Comment by thomasngataly** [comment] 2017-11-06 16:36
Hi @raphaeldealmeida 

The code inside the VAT method call an undefined siren method. See the code below 
`public function vat($spacedNationalPrefix = true)
    {
        $prefix = ($spacedNationalPrefix) ? "FR " : "FR";
        return sprintf("%s%s%s%s", $prefix, self::randomNumber(2, true), **$this->siren**($spacedNationalPrefix));
    }`

**Comment by irozgar** [comment] 2017-11-09 10:34
Hi

I also have this issue. I've seen that [this commit](https://github.com/fzaninotto/Faker/commit/cd1634afc9ddf240b32b8b4a1d998b10ef355199#diff-58fd8fc4d08a7ebe0be233c93b446906) is the one that introduced the change that broke this, because the method _siren_ does not exist in the class Payment for fr_FR locale.

**Comment by jocel1** [comment] 2017-12-08 15:32
Hi,

Same issue for me, code example to reproduce the issue is simple:

```php
$faker = Factory::create('fr_FR');
echo $faker->vat();
```

**Comment by ppelgrims** [comment] 2017-12-13 13:54
What do you think about making the method static?
```diff
    public function vat($spacedNationalPrefix = true)
    {
        $prefix = ($spacedNationalPrefix) ? "FR " : "FR";

-       return sprintf("%s%s%s%s", $prefix, self::randomNumber(2, true), $this->siren($spacedNationalPrefix));
+       return sprintf("%s%s%s%s", $prefix, self::randomNumber(2, true), Company::siren($spacedNationalPrefix));

    }
```

**Comment by fzaninotto** [comment] 2017-12-14 08:12
Fixed by #1381

**Closed by fzaninotto** 2017-12-14 08:12 UTC

**Comment by jdecool** [comment] 2018-03-14 14:33
Does this fix will be released soon

**Comment by ppelgrims** [comment] 2018-03-14 14:39
@jdecool see #1391

**Comment by jdecool** [comment] 2018-03-14 14:45
I saw it, but I can't set a dependency point to the `master` branch, even if it's only required for development.

This issue was fixed nearly 3 months ago...

**Comment by ppelgrims** [comment] 2018-03-14 14:47
I don't know what the policy or planning is for releases but I thought that could help you out in the mean time. Can't be of any more help I'm afraid.

**Comment by jdecool** [comment] 2018-03-14 14:48
No problem @ppelgrims, thanks for the suggestion :)
