### ISSUE TITLE
Generate Fake Image

### ISSUE THREAD

**Issue by mungkiice** [fzaninotto/Faker#1584] opened 2018-09-19 14:53 UTC
I tried to make dummy image file, but it doesn't return any path file and there's no single file in the directory. Then I realize that I can't even access lorempixel.com, maybe there is something wrong happened to it. Can you help me to fix that problem? or maybe there is another way to generate fake image

**Comment by fzaninotto** [comment] 2018-09-19 20:47
Duplicate of #957

**Closed by fzaninotto** 2018-09-19 20:47 UTC
