### ISSUE TITLE
state / stateAbbr the same

### ISSUE THREAD

**Issue by josephzidell** [fzaninotto/Faker#697] opened 2015-09-03 02:14 UTC
I'm generating a full address and verifying after. Data input accepts a statename, and verification happens with the abbreviation. When I generate a ->state and ->stateAbbr, they are not the same, even when using seed.

Is there a way to get the same state or is this a bug?

**Comment by vlakoff** [comment] 2015-10-06 21:27
This is normal behaviour, the two generated items are completely independent from each other.

**Comment by fzaninotto** [comment] 2015-10-06 21:35
Duplicate of #625

**Closed by fzaninotto** 2015-10-06 21:35 UTC
