### ISSUE TITLE
lorempixel.com is down, Faker image is don't working

### ISSUE THREAD

**Issue by om3rcitak** [fzaninotto/Faker#1949] opened 2020-03-01 12:00 UTC
![image](https://user-images.githubusercontent.com/5197413/75625180-ac46d280-5bcc-11ea-8586-c5dd61f96c20.png)

I tried send ping to server, server is looking running. Server accept ping but not running HTTP server.

![image](https://user-images.githubusercontent.com/5197413/75625202-d0a2af00-5bcc-11ea-8f9c-9f8e1f03e756.png)

As a result, my seeders don't working. Can you lookin immediately this issue?

---------

Idk if lorempixel.com belongs to you. If this site not belongs to you, I think you should add driver option support to faker for images.

**Comment by santoslluis** [comment] 2020-03-09 18:35
same issue is reported in faker.js and some alternatives are proposed https://github.com/Marak/faker.js/issues/641

@om3rcitak an quick-and-dirty solution can be found here https://github.com/Marak/faker.js/issues/641#issuecomment-440803727

**Comment by santoslluis** [comment] 2020-03-09 19:05
also duplicate of https://github.com/fzaninotto/Faker/issues/1884 I see

**Comment by pimjansen** [comment] 2020-03-11 11:57
Closed as in duplicate.

**Closed by pimjansen** 2020-03-11 11:57 UTC
