### ISSUE TITLE
Faker Image not working

### ISSUE THREAD

**Issue by aronquiray** [fzaninotto/Faker#1715] opened 2019-06-13 17:44 UTC
http://lorempixel.com/ website is down. so no images is being downloaded or grab.

**Comment by localheinz** [comment] 2019-06-13 19:26
See #1712 and #1713.

**Comment by hokutoasari** [comment] 2019-06-14 23:40
I use "picsum.photos" in my local env like following lines. But I think this is evil approach.

```diff
    public static function imageUrl($width = 640, $height = 480, $category = null, $randomize = true, $word = null, $gray = false)
    {
-         $baseUrl = "https://lorempixel.com/";
+        // $baseUrl = "https://lorempixel.com/";
+        $baseUrl = "https://picsum.photos/";
        $url = "{$width}/{$height}/";
```

and

```diff
            $fp = fopen($filepath, 'w');
            $ch = curl_init($url);
            curl_setopt($ch, CURLOPT_FILE, $fp);
+            curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
            $success = curl_exec($ch) && curl_getinfo($ch, CURLINFO_HTTP_CODE) === 200;
```

**Comment by t00nami** [comment] 2019-06-17 14:32
https://lorempixel.com/ up again

**Comment by pimjansen** [comment] 2019-08-21 14:38
The follow location however is a good addition. Just replacing it is a bit too much where the service runs fine right?

**Comment by localheinz** [comment] 2019-08-23 19:16
Duplicate of #1712.

**Closed by localheinz** 2019-08-23 19:16 UTC
Labels: bug
