### ISSUE TITLE
Faker sometimes generates invalid email addresses

### ISSUE THREAD

**Issue by prolic** [fzaninotto/Faker#935] opened 2016-06-10 12:00 UTC
F.e. this here:

witte.hansd.@feldmann.org

**Comment by Newman101** [comment] 2016-06-14 12:38
This can be fixed easily. The issue is in variable ```$firstNameMale``` of German locale. Looks like the email formation takes first name as it is and removes capital letters. Since one of the names (Hans D.) includes a dot, result is malformed e-mail address. I'll send a PR to fix this issue.

**Comment by Newman101** [comment] 2016-06-14 12:42
As a side note, would be good idea to amend unit tests to make sure email addresses in the future are not malformed.

**Comment by curry684** [comment] 2016-10-22 09:40
Technically that is not an invalid email address.

**Comment by KaelWD** [comment] 2017-08-06 12:31
[Tell that to the IETF:](https://tools.ietf.org/html/rfc3696#page-6)

>   Without quotes, local-parts may consist of any combination of
>   alphabetic characters, digits, or any of the special characters
>   ``! # $ % & ' * + - / = ?  ^ _ ` . { | } ~``
>   period (".") may also appear, but may not be used to start or end the
>   local part, nor may two or more consecutive periods appear.

**Comment by curry684** [comment] 2017-08-06 19:46
Granted, but by that RFC no modern mail service is compliant. Pragmatism over idealism: http://girders.org/blog/2013/01/31/dont-rfc-validate-email-addresses/

If someone wants to fix this case sure, but not for the sake of following that RFC, that would require Faker being able to generate a lot of fubar mail addresses.

**Comment by hypeJunction** [comment] 2018-04-09 08:13
Email should at least pass the ``filter_var($address, FILTER_VALIDATE_EMAIL)`` check

**Comment by Einenlum** [comment] 2018-07-07 17:37
I think this issue is solved thanks to #975, right?

**Comment by pimjansen** [comment] 2019-08-22 20:29
I think this would have solved it yes. However i think it is wise to run a cross check to be 100% sure

**Comment by pimjansen** [comment] 2019-08-23 14:24
I did a basic test with below. 0 occurences on 100k so im closing this issue

```php
<?php
require 'vendor/autoload.php';

$faker = Faker\Factory::create('de_DE');

for ($i=0; $i<100000;$i++) {
    $parts = explode('@', $faker->email);
    $lastChar = substr($parts[0], -1);
    if ($lastChar === '.') {
        die('Invalid email char');
    }
    echo '.';
}

**Closed by pimjansen** 2019-08-23 14:24 UTC

**Comment by curry684** [comment] 2019-08-26 08:33
Why not the `filter_var($address, FILTER_VALIDATE_EMAIL)` test?

**Comment by pimjansen** [comment] 2019-08-26 08:55
@curry684 there is such a test however the generator picks a random name and domain. Since some providers (in this case the german one) could give a name which end with a dot which is not allowed in the email spec.

But this is handled now in the mail generator on which no fix is needed for the email validator
