### ISSUE TITLE
Hungarian language with wrong encodings

### ISSUE THREAD

**Issue by bertalanimre** [fzaninotto/Faker#1733] opened 2019-07-17 13:19 UTC
If I try to anonymize with hu_HU locale, then in the database I have wrong characters for the special characters place like: á é ű ú ő......

Instead, I see: Ã¡, Å±, Ã¡, ......

I have dried to create the database with `UTF8`, `Latin1`, `UTF8_Hungarian_CI`, none helped.

**Comment by pimjansen** [comment] 2019-08-27 11:57
I did a local test and seems that the data is passed correctly from `Faker`. This is either an issue in your database configuration or connection towards that database. For further support i suggest to raise an issue at Stackoverflow.

Since this is not a bug i will close this issue. Further followup can be done via stackoverflow if required

**Closed by pimjansen** 2019-08-27 11:57 UTC
