### ISSUE TITLE
e164PhoneNumber Generates Invalid Numbers

### ISSUE THREAD

**Issue by kiler129** [fzaninotto/Faker#1510] opened 2018-06-18 16:22 UTC
The E.164 phone number generator (and probably others?) sometimes generates invalid phone number which is problematic while using in unit tests.

Examples:
 - https://libphonenumber.appspot.com/phonenumberparser?number=%2B3840285337938&country=US
 - https://libphonenumber.appspot.com/phonenumberparser?number=%2B2969380332191&country=US
 - https://libphonenumber.appspot.com/phonenumberparser?number=%2B2952890379705&country=US

Also it seems some numbers while not totally invalid they're not following locale specific rules:
 - https://libphonenumber.appspot.com/phonenumberparser?number=%2B3068203433313&country=US
 - https://libphonenumber.appspot.com/phonenumberparser?number=%2B7547960956891&country=US
 - https://libphonenumber.appspot.com/phonenumberparser?number=%2B7126293569845&country=US

I cannot say it's not a bug in Google's `libphonenumber`, but the library is very old, robust and used by Android phones all over the world ;)

**Comment by ppelgrims** [comment] 2018-06-18 17:10
See my reply in #1488

**Comment by fzaninotto** [comment] 2018-06-25 11:58
Duplicate of #1488

**Closed by fzaninotto** 2018-06-25 11:58 UTC
