### ISSUE TITLE
LoremPixel is unusable as an image source

### ISSUE THREAD

**Issue by kiler129** [fzaninotto/Faker#1503] opened 2018-06-06 17:25 UTC
For days now LoremPixel response time is >20s. Maybe we should think about changing it?

https://placeholder.com has been pretty stable for long time for non context-specific images, https://placeimg.com allows context to be specified.

**Comment by tomzx** [comment] 2018-06-07 02:18
Duplicate of #957 and #1484.

**Closed** 2018-06-14 15:00 UTC
