### ISSUE TITLE
$faker->image() does not work via curl

### ISSUE THREAD

**Issue by Charliiee** [fzaninotto/Faker#1246] opened 2017-06-29 17:24 UTC
I get an error while fetching the image from lorempixel.com saying hostname was not found in dns cache.
Here the error I get from the command `curl -v http://lorempixel.com`:
```
* Hostname was NOT found in DNS cache
*   Trying 37.61.200.188...
*   Trying 2a01:488:67:1000:253d:c8bc:0:1...
* connect to 2a01:488:67:1000:253d:c8bc:0:1 port 80 failed: Network is unreachable
* Failed to connect to lorempixel.com port 80: Network is unreachable
* Closing connection 0
curl: (7) Failed to connect to lorempixel.com port 80: Network is unreachable
```
The problem is that ping to lorempixel.com is OK as well as the curl to any other site, e.g. https://www.google.com

Furthermore, when I comment the part of code that uses curl and use the `copy` instead it works perfectly.

**Comment by fzaninotto** [comment] 2017-07-03 16:01
Can't reproduce, closing.

**Closed by fzaninotto** 2017-07-03 16:01 UTC
