### ISSUE TITLE
Resource temporarily unavailable

### ISSUE THREAD

**Issue by mohd-isa** [fzaninotto/Faker#1402] opened 2018-01-12 14:09 UTC
There is some issue with image generation. I am always getting this error

```
unlink(storage/app/public/events\fb2b6250b3ba1ebdaab1fdf57db406c3.jpg): Resource temporarily unavailable
```

It seems the download fails at some point and it tries to unlink the file.

Here is how I try to generate it

```
$faker = Faker\Factory::create();

$faker->image('storage/app/public/events');
```

I am using v1.7.1

**Comment by tomzx** [comment] 2018-01-12 19:59
Hello,

It would be useful if you could provide more detail/context as to what you're doing.

**Comment by mohd-isa** [comment] 2018-01-13 08:51
I've updated the post with the code snippet & version.

**Comment by fzaninotto** [comment] 2018-01-15 21:06
Yes, the issue is fixed by e048b88. No, I haven't any forecast on the next release.

**Comment by MizaelMelo** [comment] 2018-04-22 19:10
Thanks, @contik1

**Comment by alexcoroza** [comment] 2018-05-15 15:13
I tried the fix suggested in [e048b88](https://github.com/fzaninotto/Faker/commit/e048b8863786bf0d83689dee2f1b964879ca6a19) and the error message is gone but it doesnt generating any image. it will generate an "unfinished file" in the directory and then update/overwrite it with another "unfinished file" and will be deleted once the processing is finished

**Comment by alexcoroza** [comment] 2018-05-15 16:47
After searching in this repositories' issues, I think it is related to [lorepixel.com is down](https://github.com/fzaninotto/Faker/issues/1484). I believe this issue is already fixed because I managed to generate images last week but then again today I failed. I visited https://lorempixel.com and it I can confirm it is down and is causing all these issues.

**Comment by fatonsopa** [comment] 2018-05-22 10:21
This happens when OpenSSL is not working properly in your system. 

What I found is that if you manually set certification path in Image.php Line 85, it works:
<pre>
<code>
$certificate_location = 'C:\certs\cacert.pem';
curl_setopt($ch, CURLOPT_CAINFO, $certificate_location);
</code>
</pre>


It also works if you disable SSL verification, by adding this line in Image.php:
<pre>
<code>
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
</code>
</pre>


OR

if you bypass curl method and goes directory to copy method. This is done by replacing
<pre>
<code>
if(function_exists('curl_exec')){
</code>
</pre>

with

<pre>
<code>
if(false){
</code>
</pre>


However, be aware that this is only a workaround and changes may be overwritten when you do composer update. Therefore, I may be a good idea to do a PR that goes to the copy method if CURL fails.

**Comment by fatonsopa** [comment] 2018-05-22 10:31
Just fixed it via a PR https://github.com/fzaninotto/Faker/pull/1490. Hope someone will approve it :)

**Comment by david-saint** [comment] 2018-06-20 09:47
I think the issue is your folder is currently open when running the command or something...
I tried like 20 times with my folder open and kept on getting the errors but once I closed the folder it succeeded

**Comment by pimjansen** [comment] 2019-08-27 18:50
Since the issue is stale and the original bug was resolved already i will now close this issue.

**Closed by pimjansen** 2019-08-27 18:50 UTC
