### ISSUE TITLE
mt_rand() generates minus number in Base::randomElements (windows only)

### ISSUE THREAD

**Issue by daveyand** [fzaninotto/Faker#1379] opened 2017-12-11 12:54 UTC
i am having a strange issue with using the Faker to generate fixtures within Alice. I'm on PHP 7.1.8 and windows. 

When i run the fixtures i get an undefined index error. 

This seems to occur only on Windows and not Mac OSX or linux. 

This also is only an issue if AllowDuplicates == false. 

i have added an echo after the mt_rand() call on line 184 Base.php and i get the following when i run the fixtures:

Num: 0 | High Key: 1
Num: 11 | High Key: 1567
Num: -132 | High Key: 472

I cant seem to figure out what the hell is happening and hoping someone here can help me at least work out what it isnt.

**Comment by tomzx** [comment] 2017-12-14 22:47
Hello @daveyand,

Can you specify which version of Faker you are using?

As far as the code goes, if `$highKey` where to be negative, `mt_rand` would generate an exception.

Out of curiosity, are you using php from cygwin?

**Comment by webkim** [comment] 2017-12-30 21:48
I am experiencing this issue also.
 
$highKey seems to be positive (248) but $num = mt_rand(0, $highKey); returns -107 on every run.
If i duplicate row 186 on Base.php ($num = mt_rand(0, $highKey);) the code will run fine. (not sure why)
Strange thing is that if i make those duplicate rows, second execution always returns 56.

I made debug php which prints mt_rand values and it seems to work fine.

Running laravel 5.5.18 and faker 1.7.0
My php version is 7.1.8 from windows.php.net

**Comment by tomzx** [comment] 2018-01-05 02:51
@daveyand, @webkim, can one of you create a reproducible piece of code which generates this issue?

**Comment by webkim** [comment] 2018-01-05 09:55
[testproj.zip](https://github.com/fzaninotto/Faker/files/1606176/testproj.zip)

Attached files will replicate the issue

**Comment by tomzx** [comment] 2018-01-05 18:37
I've tried what @webkim provided using a freshly downloaded `C14 x64 Thread Safe` php 7.1.18 and I can't reproduce.

Can you guy share your `php -v` as well as your `phpinfo` output?

**Comment by webkim** [comment] 2018-01-05 19:15
[phpinfo.zip](https://github.com/fzaninotto/Faker/files/1607643/phpinfo.zip)

php -v 
PHP 7.1.8 (cli) (built: Aug  1 2017 21:10:46) ( ZTS MSVC14 (Visual C++ 2015) x86 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans


Contents of phpinfo in zipfile

**Comment by Plant-for-the-Planet** [comment] 2018-01-11 00:21
I have the same issue.
Funny enough, no problems on Win7 but I also get a negative number after deploying to a Linux server.
I am using fzaninotto/faker v1.7.1.

Debugging line 185 of fzaninotto/faker/src/Faker/Provider/Base.php during fixture loading gives me:
```
$num = mt_rand(0, $highKey); 

$highKey=1 $num=0
$highKey=1 $num=0
$highKey=1567 $num=-438
```
`# php -v on Linux:`
`PHP 7.1.6 (cli) (built: Jun 23 2017 07:35:25) ( NTS )`
phpinfo.txt [phpinfo.txt](https://github.com/fzaninotto/Faker/files/1620809/phpinfo.txt)

Under Win7 I have tried to reproduce the error with different PHP versions without success:
(I am using the x64 versions unlike @webkim though)
```
PHP 7.1.2 (cli) (built: Feb 14 2017 21:24:49) ( ZTS MSVC14 (Visual C++ 2015) x64 )
PHP 7.1.8 (cli) (built: Aug  1 2017 20:56:53) ( ZTS MSVC14 (Visual C++ 2015) x64 )
PHP 7.1.13 (cli) (built: Jan  3 2018 20:04:41) ( ZTS MSVC14 (Visual C++ 2015) x64 )
```

Running `mt_rand()` interactively on the Linux server under CLI, with the same PHP version I run my Symfony command  `php bin/console hautelook:fixtures:load`, produces no errors neither.

```
# php -a
Interactive mode enabled

<?php
echo mt_rand(0, 1) . "\n";
echo mt_rand(0, 1) . "\n";
echo mt_rand(0, 1567) . "\n";
?>
0
1
297
```

**Comment by tomzx** [comment] 2018-01-11 02:30
Alright, after a lot of testing, it appears this was a bug in PHP x86 up to 7.1.12. It is fixed in 7.1.13.

See https://bugs.php.net/bug.php?id=75514.

**Comment by fzaninotto** [comment] 2018-01-11 10:15
OK, so closing this bug.

**Closed by fzaninotto** 2018-01-11 10:15 UTC

**Comment by Plant-for-the-Planet** [comment] 2018-01-12 03:13
Do you think it would be possible for me to fork and replace mt_rand with something else until my hosting provider offers to use PHP 7.1.13 or higher (I'm currently stuck at 7.1.10). Do you have an idea on how this could be done and estimate how much work it would require?

**Comment by AlkisStamos** [comment] 2018-07-06 07:59
Hello, sorry for commenting on a closed issue, I bumped into a similar bug today (using PHP7.2). The problem seems to be coming from the seed method of the Faker\Generator class which seeds the mt_rand function using the MT_RAND_PHP mode (for later php versions). Changing the mode to MT_RAND_MT19937 seems to be working for me. Hope this helps, have a nice day :)
