### ISSUE TITLE
randomFloat doesn't work 100%

### ISSUE THREAD

**Issue by approached** [fzaninotto/Faker#985] opened 2016-08-05 10:13 UTC
randomFloat goes doesn't work 100%

Code:
```php
dd($faker->randomFloat(3, 0, 1000));
```

Test:
```bash
vagrant@laravel:/vagrant/IALaravel$ phpunit tests/integration/Shop/
PHPUnit 5.4.4 by Sebastian Bergmann and contributors.

Error:         No code coverage driver is available

833.359
vagrant@laravel:/vagrant/IALaravel$ phpunit tests/integration/Shop/
PHPUnit 5.4.4 by Sebastian Bergmann and contributors.

Error:         No code coverage driver is available

343.73
vagrant@laravel:/vagrant/IALaravel$ phpunit tests/integration/Shop/
PHPUnit 5.4.4 by Sebastian Bergmann and contributors.

Error:         No code coverage driver is available

887.4160000000001
```

Same problem with two decimal digits. Sometimes i become a value like this: _887.4160000000001_

**Comment by Newman101** [comment] 2016-08-08 21:43
I reviewed the code in question. Since we are talking about a function which returns value inside ```round```, it should be rounded: 

```php
return round($min + mt_rand() / mt_getrandmax() * ($max - $min), $nbMaxDecimals);
```

There are various explanations why this thing happens. 

First and foremost: are your variables passed to function as strings?  If so, the ```round()``` does not always work: http://stackoverflow.com/questions/3726721/php-floating-number-precision

Another possible reason for this is that if number is negative and precision is bigger than the actual number of digits after comma, you get into trouble? 

http://php.chinaunix.net/manual/sl/function.round.php#100994

If this is true for non-negative number, then we might have a problem. 

There is also a bug (feature, really...) which means that for certain values, round() returns the value in exponential notation instead of the usual decimal format. Please see the URL below. 

https://bugs.php.net/bug.php?id=44223

My best guess is that this has something to do with the last one. Certainly worth investigating. I'm trying to reproduce the issue ASAP, once I get some results I'll post them here.

**Comment by Newman101** [comment] 2016-08-08 22:13
OK, here's some results. Code: 

```php
<?php

	require_once "vendor/autoload.php";

	$faker = Faker\Factory::create();

	foreach(range(1, 10000) as $x) {
		echo $faker->randomFloat(3, 0, 1000) . "<br/>";
	}
?>
```

Results in the text file. Maybe this has something to do with that ```dd``` method you are invoking?

[faker_results.txt](https://github.com/fzaninotto/Faker/files/407848/faker_results.txt)

**Comment by Newman101** [comment] 2016-08-08 22:22
Attempted the following too: 

```php
<?php

	require_once "vendor/autoload.php";

	$faker = Faker\Factory::create();

	foreach(range(1, 100000) as $x) {
		var_dump($faker->randomFloat(3, 887, 888));
	}
?>
```

Results below. One of the values causing error appeared and looks like it was rounded normally. 

[faker_results_var_dump.txt](https://github.com/fzaninotto/Faker/files/407859/faker_results_var_dump.txt)

**Comment by approached** [comment] 2016-08-09 07:21
dd is a typical laravel function.

dd:
```php
    function dd()
    {
        array_map(function ($x) {
            (new Dumper)->dump($x);
        }, func_get_args());

        die(1);
    }
```

Dumper class:
```php
<?php

namespace Illuminate\Support\Debug;

use Symfony\Component\VarDumper\Dumper\CliDumper;
use Symfony\Component\VarDumper\Cloner\VarCloner;

class Dumper
{
    /**
     * Dump a value with elegance.
     *
     * @param  mixed  $value
     * @return void
     */
    public function dump($value)
    {
        if (class_exists(CliDumper::class)) {
            $dumper = 'cli' === PHP_SAPI ? new CliDumper : new HtmlDumper;

            $dumper->dump((new VarCloner)->cloneVar($value));
        } else {
            var_dump($value);
        }
    }
}
```

I think there a error in the CliDumper class https://github.com/symfony/var-dumper/blob/master/Dumper/CliDumper.php

composer.lock:
```json
        {
            "name": "fzaninotto/faker",
            "version": "v1.6.0",
            "source": {
                "type": "git",
                "url": "https://github.com/fzaninotto/Faker.git",
                "reference": "44f9a286a04b80c76a4e5fb7aad8bb539b920123"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/fzaninotto/Faker/zipball/44f9a286a04b80c76a4e5fb7aad8bb539b920123",
                "reference": "44f9a286a04b80c76a4e5fb7aad8bb539b920123",
                "shasum": ""
            },
            "require": {
                "php": "^5.3.3|^7.0"
            },
            "require-dev": {
                "ext-intl": "*", 
                "phpunit/phpunit": "~4.0",
                "squizlabs/php_codesniffer": "~1.5"
            },
            "type": "library",
            "extra": {
                "branch-alias": []
            },
            "autoload": {
                "psr-4": {
                    "Faker\\": "src/Faker/"
                }    
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "François Zaninotto"
                }    
            ],
            "description": "Faker is a PHP library that generates fake data for you.",
            "keywords": [
                "data",
                "faker",
                "fixtures"
            ],
            "time": "2016-04-29 12:21:54"
        }
```

**Comment by Newman101** [comment] 2016-08-23 10:10
Hi. Thank you for this. I can have a look at this for you. It might actually have something to do with the dumper class.

Core reasoning: ```var_dump``` function uses ```precision``` from ```php.ini``` to display float value. So if you ```var_dump``` a result of ```var_dump```, it might mess up the float values. I need to test this out to see if this is actually the case.

**Comment by fzaninotto** [comment] 2016-10-07 05:14
Closing, as there is no sure sign that this is a Faker bug. feel free to reopen if you can provide a failing test case.

**Closed by fzaninotto** 2016-10-07 05:14 UTC

**Comment by Koudy** [comment] 2017-11-08 15:02
I have this problem too. 
Reproduce in here: #650
