### ISSUE TITLE
Request $min for Datetime

### ISSUE THREAD

**Issue by lauhakari** [fzaninotto/Faker#736] opened 2015-10-10 13:32 UTC
It would be nice if there was a way if defining a $min value on dates also, not just $max.
Sometimes you want to dates/times to only be in the future =)

**Comment by jmauerhan** [comment] 2015-10-10 22:15
I would think that would have to be a new function, otherwise it would get confusing. Maybe like `dateTimeAfter($min)` ?

**Comment by fzaninotto** [comment] 2015-10-12 15:28
Duplicate of #726

**Closed by fzaninotto** 2015-10-12 15:28 UTC
