### ISSUE TITLE
Test fail in some cases - Provider InternetTest en_ZA

### ISSUE THREAD

**Issue by Ultim4T0m** [fzaninotto/Faker#1119] opened 2016-12-17 10:43 UTC
I'm having this failure, so my PR cant' be merged.

> There was 1 failure:
> 1) Faker\Test\Provider\InternetTest::testEmailIsValid with data set #21 ('en_ZA')
> Failed asserting that 'mr..willemse@gmail.com' matches PCRE pattern "/^(?!(?:(?:\x22?\x5C[\x00-\x7E]\x22?)|(?:\x22?[^\x5C\x22]\x22?)){255,})(?!(?:(?:\x22?\x5C[\x00-\x7E]\x22?)|(?:\x22?[^\x5C\x22]\x22?)){65,}@)(?:(?:[\x21\x23-\x27\x2A\x2B\x2D\x2F-\x39\x3D\x3F\x5E-\x7E]+)|(?:\x22(?:[\x01-\x08\x0B\x0C\x0E-\x1F\x21\x23-\x5B\x5D-\x7F]|(?:\x5C[\x00-\x7F]))*\x22))(?:\.(?:(?:[\x21\x23-\x27\x2A\x2B\x2D\x2F-\x39\x3D\x3F\x5E-\x7E]+)|(?:\x22(?:[\x01-\x08\x0B\x0C\x0E-\x1F\x21\x23-\x5B\x5D-\x7F]|(?:\x5C[\x00-\x7F]))*\x22)))*@(?:(?:(?!.*[^.]{64,})(?:(?:(?:xn--)?[a-z0-9]+(?:-+[a-z0-9]+)*\.){1,126}){1,}(?:(?:[a-z][a-z0-9]*)|(?:(?:xn--)[a-z0-9]+))(?:-+[a-z0-9]+)*)|(?:\[(?:(?:IPv6:(?:(?:[a-f0-9]{1,4}(?::[a-f0-9]{1,4}){7})|(?:(?!(?:.*[a-f0-9][:\]]){7,})(?:[a-f0-9]{1,4}(?::[a-f0-9]{1,4}){0,5})?::(?:[a-f0-9]{1,4}(?::[a-f0-9]{1,4}){0,5})?)))|(?:(?:IPv6:(?:(?:[a-f0-9]{1,4}(?::[a-f0-9]{1,4}){5}:)|(?:(?!(?:.*[a-f0-9]:){5,})(?:[a-f0-9]{1,4}(?::[a-f0-9]{1,4}){0,3})?::(?:[a-f0-9]{1,4}(?::[a-f0-9]{1,4}){0,3}:)?)))?(?:(?:25[0-5])|(?:2[0-4][0-9])|(?:1[0-9]{2})|(?:[1-9]?[0-9]))(?:\.(?:(?:25[0-5])|(?:2[0-4][0-9])|(?:1[0-9]{2})|(?:[1-9]?[0-9]))){3}))\]))$/iD".
> /home/travis/build/fzaninotto/Faker/test/Faker/Provider/InternetTest.php:51
> 

Build here : https://travis-ci.org/fzaninotto/Faker/jobs/184747981

**Comment by vlakoff** [comment] 2016-12-17 15:49
It is caused by a `'Mr. '` in en_ZA\Person provider.

Not the first time such issue happens, please see #975.

**Comment by vlakoff** [comment] 2017-09-20 16:33
#975 has been merged, such issues can't no longer happen.

This issue can be closed :)

**Closed** 2017-09-22 09:30 UTC
