### ISSUE TITLE
v1.5.0: Generators cannot return values using "return"...

### ISSUE THREAD

**Issue by eventbase-web** [fzaninotto/Faker#855] opened 2016-03-15 03:41 UTC
Recently updated to Faker 1.5 and got the following error when running unit tests:

`Generators cannot return values using "return" in /src/mylib/vendor/fzaninotto/faker/src/Faker/Provider/Base.php on line 480`

PHPUnit 5.2.11

Would like some help debugging the issue, or ruling out Faker as the cause. Reverting to v1.4.0 resolves the issue.

**Comment by eventbase-web** [comment] 2016-03-15 19:07
Appears to be related to my having upgraded another dependency: codeception/aspect-mock from 0.5.5 to 1.0.0.

0.5.5 uses goaop/framework 0.6.1, 1.0.0 uses goaop/framework 1.0.2. Something about this change is causing the issue. It's strange because Faker obviously doesn't have this dependency, so it's something I'm doing with Faker interacting with Aspect Mock.

This is probably not something Faker can resolve, but I'm going to leave this issue open for a bit while I attempt to resolve it, in case it helps other users.

**Comment by eventbase-web** [comment] 2016-03-15 20:34
May be related to this issue:
https://github.com/Codeception/AspectMock/pull/66

Though doesn't make sense to me yet, because Base is not returning a Generator on line 480, it's returning a string.

**Comment by fzaninotto** [comment] 2016-03-16 09:27
Can't reproduce the error, closing. Feel free to reopen if you have more details about the problem.

**Closed by fzaninotto** 2016-03-16 09:27 UTC
